### ISSUE TITLE
Xiaomi AX1800

### ISSUE THREAD

**Issue by proxer05** [openwrt-dev/ci-ipq60xx#1]
Hi.
I see you're working at Xiaomi Rm1800(m59 platform). Can I verify it have same hardware as Xiaomi ax1800/ra67(m67 platform)? 
- IPQ60xx
- QCA5052/5022
- IPQ8075
- M15T2G16128A

**Comment by pexcn** [comment]
This firmware only work on Xiaomi AX1800/Redmi AX5, not work to m59 platform.
You can try this artifacts https://github.com/openwrt-dev/ci-ipq60xx/actions/runs/6762242713

**Comment by pexcn** [comment]
You can go to this issue to view more details: https://github.com/JiaY-shi/openwrt/issues/14

**Comment by proxer05** [comment]
> This firmware only work on Xiaomi AX1800/Redmi AX5, not work to m59 platform.
> You can try this artifacts https://github.com/openwrt-dev/ci-ipq60xx/actions/runs/6762242713

Ohh. Nice then. I got confused by rm1800 in commit messages😅. What's current status of your build?

**Comment by pexcn** [comment]
> Ohh. Nice then. I got confused by rm1800 in commit messages😅.

My DTS was modified based on [this](https://github.com/coolsnowwolf/openwrt-gl-ax1800/blob/master/target/linux/ipq60xx/files-4.4/arch/arm64/boot/dts/qcom/qcom-ipq6018-rm1800.dts) version, but I will change it to `AX1800` in the future.

> What's current status of your build?

Two bugs, see [here](https://github.com/JiaY-shi/openwrt/issues/14#issuecomment-1793766030) for details.

**Comment by pexcn** [comment]
Hi, @proxer05 how's the effect? Have you found any other bugs?

**Comment by proxer05** [comment]
I'm gonna flash it on Friday as I'm not at home atm. Can I flash it using sysupgrade on stock?

**Comment by proxer05** [comment]
Also your bug with stuck on sbl after soft reboot might be related to qcom_smc? Check patches from ipq40xx

**Comment by pexcn** [comment]
> I'm gonna flash it on Friday as I'm not at home atm. Can I flash it using sysupgrade on stock?

Maybe not. I have only tried using a third-party uboot to flash using the factory image.
Another thing worth noting is that it requires your AX1800 to have at least 512MB of RAM, this means you have to upgrade its RAM.

**Comment by pexcn** [comment]
You can try this third-party uboot, it should be possible to flash it via stock firmware:
```sh
# make sure uboot.bin md5 is 9b36b989bff3da67b1e95c85c179c237

mtd write uboot.bin /dev/mtd7
mtd verify uboot.bin /dev/mtd7
```
[uboot.zip](https://github.com/diy-openwrt/ci-ipq60xx/files/13303628/uboot.zip)

In addition, after upgrading the RAM, you need to flash the corresponding CDT to recognize it.
```sh
cat /proc/mtd | grep CDT
mtd write /tmp/tmp/CDT-AX1800_1G.bin /dev/mtd5
mtd verify /tmp/tmp/CDT-AX1800_1G.bin /dev/mtd5
```
[CDT.zip](https://github.com/diy-openwrt/ci-ipq60xx/files/13303642/CDT.zip)

**Comment by pexcn** [comment]
> Also your bug with stuck on sbl after soft reboot might be related to qcom_smc? Check patches from ipq40xx

Can you provide links to relevant patches?

**Comment by proxer05** [comment]
> 
>Another thing worth noting is that it requires your AX1800 to have at least 512MB of RAM, this means you have to upgrade its RAM.

Which one you used? Does it need to be Micron one?

**Comment by pexcn** [comment]
> Which one you used? Does it need to be Micron one?

I use Micron D9STQ (MT41K512M16HA-125:A) 1GB, you can see https://github.com/Lvellios/OpenWrt-IPQ/ for detail.
