### ISSUE TITLE
Removed wifi?

### ISSUE THREAD

**Issue by breeze303** [openwrt-dev/ci-ipq60xx#2]
No wifi
![image](https://github.com/openwrt-dev/ci-ipq60xx/assets/122870904/197bbfb9-fa4e-4f9c-81ae-25490574aac6)

**Comment by breeze303** [comment]
为啥我刷这下载的包没wifi选项奇怪了

**Comment by pexcn** [comment]
刷了AX5的？这个我没测试过

**Comment by breeze303** [comment]
ax5/ax1800的都没有

**Comment by breeze303** [comment]
![image](https://github.com/openwrt-dev/ci-ipq60xx/assets/122870904/c31fe99a-db3e-4d4a-9b98-511a9a5b6078)
本地编译的话会提示这个m4这个工具出错，不知道咋解决，你ci的docker该怎么用

**Comment by pexcn** [comment]
直接fork本仓库改些配置就能用，就几个文件

**Comment by pexcn** [comment]
![image](https://github.com/openwrt-dev/ci-ipq60xx/assets/4590439/d8294364-06bb-4bb2-8067-29d8c8c59d1c)
Redmi AX5已测试，WiFi正常。
